### ISSUE TITLE
[feature] Better integration with external identity provider

### ISSUE THREAD

**Issue by ArcherSeven** [siderolabs/omni#198]
### Problem Description

Currently, our integration with our Azure AD is through SAML, and the permissions are set by role definitions on the first login of a user, however those permissions are not updated as the user gets new permissions unless the user in Omni is deleted.

### Solution

Any solution that results in the permissions associated to the AD groups of a user being applied to that user on every login, even if they have changed.

### Alternative Solutions

Potentially: don't track users in Omni directly, just use the users in the identity provider.

**Comment by utkuozdemir** [comment]
Thank you for the feedback.
This is actually by design, to avoid getting locked out of Omni or having accidental role changes. 

The `labels` on the `Identity` resource though are updated on each login, and they can be used in `labelselectors` of ACLs to allow users to "impersonate" a role when they are targeting a specific set of clusters.  It is not exactly the same as role assignment, but in the scope of a cluster, they effectively work the same as roles. Docs:
- https://omni.siderolabs.com/docs/how-to-guides/how-to-manage-acls/
- https://omni.siderolabs.com/docs/reference/acls/

However we are aware that ACLs might complicate things, so we could re-evaluate the decision of doing the label->role assignment only once, maybe with an opt-in setting.
